# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: piers.rocks - Piers's Blog
email: piers@piers.rocks
description: > # this means to ignore newlines until "baseurl:"
  Piers's musings related to his github projects.  Internet of Things
  (IoT), embedded programming, heating systems, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piers.rocks/" # the base hostname & protocol for your site
twitter_username: PiersFinlayson
github_username:  piersfinlayson

# Build settings
markdown: kramdown
