title: piers.rocks - Piers's Blog
email: piers@piers.rocks
description: >
  Piers's musings related to his github projects.  Internet of Things
  (IoT), embedded programming, heating systems, ...
baseurl: ""
url: "https://piers.rocks/"
twitter_username: PiersFinlayson
github_username:  piersfinlayson
markdown: kramdown
